In [1]:
import numpy as np
import pandas as pd

In [13]:
car = pd.read_csv('car.data')
car

buying  maint  doors  persons  lug_boot  safety  target
0          1      1      2        2         0       4    1210
1          1      1      2        2         0       3    1210
2          1      1      2        2         0       2    1210
3          1      1      2        2         3       4    1210
4          1      1      2        2         3       3    1210
...      ...    ...    ...      ...       ...     ...     ...
1723       4      4      6        6         3       3      69
1724       4      4      6        6         3       2      65
1725       4      4      6        6         9       4    1210
1726       4      4      6        6         9       3      69
1727       4      4      6        6         9       2      65

[1728 rows x 7 columns]

In [3]:
car.describe()

buying        maint        doors      persons     lug_boot  \
count  1728.000000  1728.000000  1728.000000  1728.000000  1728.000000   
mean      2.500000     2.500000     3.750000     4.000000     4.000000   
std       1.118358     1.118358     1.479448     1.633466     3.742741   
min       1.000000     1.000000     2.000000     2.000000     0.000000   
25%       1.750000     1.750000     2.750000     2.000000     0.000000   
50%       2.500000     2.500000     3.500000     4.000000     3.000000   
75%       3.250000     3.250000     4.500000     6.000000     9.000000   
max       4.000000     4.000000     6.000000     6.000000     9.000000   

            safety       target  
count  1728.000000  1728.000000  
mean      3.000000   937.813657  
std       0.816733   423.007142  
min       2.000000    65.000000  
25%       2.000000   384.000000  
50%       3.000000  1210.000000  
75%       4.000000  1210.000000  
max       4.000000  1210.000000

In [4]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(car, test_size=0.1, random_state=42)

In [5]:
train_set

buying  maint  doors  persons  lug_boot  safety  target
212        1      2      6        6         3       2    1210
618        2      2      4        6         9       4    1210
944        3      1      4        6         9       2     384
1574       4      3      4        2         9       2    1210
414        1      4      6        4         0       4    1210
...      ...    ...    ...      ...       ...     ...     ...
1130       3      3      3        6         3       2      65
1294       3      4      6        6         9       3      69
860        2      4      6        6         3       2     384
1459       4      2      4        2         0       3    1210
1126       3      3      3        6         0       3     384

[1555 rows x 7 columns]

In [6]:
test_set

buying  maint  doors  persons  lug_boot  safety  target
599        2      2      4        2         3       2    1210
1201       3      4      2        4         3       3     384
628        2      2      6        2         9       3    1210
1498       4      2      6        4         3       3     384
1263       3      4      4        6         3       4    1210
...      ...    ...    ...      ...       ...     ...     ...
617        2      2      4        6         3       2     384
1175       3      3      6        4         3       2      65
1394       4      1      6        4         9       2     384
270        1      3      4        2         0       4    1210
743        2      3      6        4         3       2     384

[173 rows x 7 columns]

In [7]:
train_features = train_set.drop('target', axis = 1)
train_lables = train_set['target'].copy()

test_features = test_set.drop('target', axis =1)
test_lables = test_set['target'].copy()

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
model = DecisionTreeClassifier(max_depth=9, random_state=0)
model.fit(np.array(train_features), np.array(train_lables))
test_features_arr = np.array(test_features)
predictions = model.predict(test_features_arr)
predictions

array([1210,  384, 1210,  384, 1210,  384, 1210, 1210, 1210, 1210,   65,
        384, 1210, 1210, 1210, 1210, 1210, 1210, 1210,  384, 1210,  384,
        384, 1210,  384, 1210, 1210, 1210, 1210, 1210,  384, 1210, 1210,
       1210,  384,  384,   69, 1210, 1210, 1210, 1210, 1210,  384,  384,
         69,   65, 1210, 1210, 1210, 1210, 1210, 1210,  384, 1210, 1210,
       1210, 1210, 1210, 1210,   69, 1210,  384, 1210, 1210,  384,   65,
       1210,  384,  384, 1210, 1210, 1210, 1210, 1210,   65,   69, 1210,
       1210, 1210, 1210,   65, 1210, 1210,  384,   65,  384, 1210,  384,
         69,  384, 1210,   69, 1210, 1210, 1210,   69, 1210, 1210, 1210,
        384, 1210, 1210, 1210, 1210,   69,   69,  384, 1210, 1210,  384,
       1210, 1210, 1210, 1210, 1210,  384,   69, 1210, 1210, 1210, 1210,
         65, 1210,  384,  384, 1210,   69, 1210, 1210, 1210, 1210, 1210,
        384, 1210, 1210,  384, 1210,   65, 1210, 1210, 1210,  384, 1210,
        384, 1210,  384, 1210, 1210, 1210, 1210,  3

In [10]:
test_lables_arr = np.array(test_lables)
test_lables_arr

array([1210,  384, 1210,  384, 1210,  384, 1210, 1210, 1210, 1210,   65,
        384, 1210, 1210, 1210, 1210, 1210, 1210, 1210,  384, 1210,  384,
        384, 1210,  384, 1210, 1210, 1210, 1210, 1210,  384, 1210, 1210,
       1210,  384,  384,   69, 1210, 1210, 1210, 1210, 1210,  384,  384,
        384,   65, 1210, 1210, 1210, 1210, 1210, 1210,  384, 1210, 1210,
       1210, 1210, 1210, 1210,   69, 1210,  384, 1210, 1210,  384,   65,
       1210,  384,  384, 1210, 1210, 1210, 1210, 1210,  384,   65, 1210,
       1210, 1210, 1210,   65, 1210, 1210,  384,   65,  384, 1210,  384,
         65,  384, 1210,   69, 1210, 1210, 1210,   69, 1210, 1210, 1210,
        384, 1210, 1210, 1210, 1210,  384,   69,  384, 1210, 1210,  384,
       1210, 1210, 1210, 1210, 1210,  384,   69, 1210, 1210, 1210, 1210,
         69, 1210,  384,  384, 1210,  384, 1210, 1210, 1210, 1210, 1210,
        384, 1210, 1210,  384, 1210,   65, 1210, 1210, 1210,  384,  384,
        384, 1210,  384, 1210, 1210, 1210, 1210,  3

In [11]:
count = 0
for _ in range(len(predictions)):
    if(predictions[_] != test_lables_arr[_]):
        count = count + 1
count

8

In [12]:
test = [3,4,3,6,3,2]
model.predict([test])

array([65], dtype=int64)